spring:
  application:
    name: ${APPLICATION_NAME}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: ${HIBERNATE_SHOW_SQL}
    hibernate:
      ddl-auto: ${HIBERNATE_HBM2DDL_AUTO}

security:
  bcrypt:
    secret: ${BCRYPT_PASSWORD_SECRET}