package pl.minecodes.mmetrics.product;

public enum ProductType {

  MINECRAFT_PLUGIN,
  MINECRAFT_MOD,
  MINECRAFT_SERVER,
  JAVA_APPLICATION,
  WEB_APPLICATION,
  ANDROID_APPLICATION,
  IOS_APPLICATION,
  DESKTOP_APPLICATION,
  OTHER

}
